name: kind_words
description: "An awesome project to connect with people.."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  animated_bottom_navigation_bar: ^1.3.3
  appinio_swiper: ^2.1.0
  draggable_home: ^1.0.5
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
