name: kind_words
description: "An awesome project to connect with people.."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.2.0
  provider: ^6.1.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
